
###
POST http://localhost:8080/api/oauth2/authorize
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Basic YWRtaW4xNjY1MTQ1MTgzNzQ2OmRjZDY3M2JiLTZmODItNDNjNS05NzljLWRmMzBkYTA2MjU2Mg==
###


###
POST http://localhost:8080/api/cannacomply/CreateFarmService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "name": "New test farm",
  "latitude": "23.4543",
  "longitude": "-33.4432",
  "logoData": "year",
  "type": "NORMAL FARM"
}
###

###
POST http://localhost:8080/api/cannacomply/UpdateFarmService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "c96f40ee-d211-4075-8d37-635febe1e3f4",
  "name": "New test farm2",
  "latitude": "23.4543-2",
  "longitude": "-33.4432-2",
  "logoData": "year2",
  "type": "NORMAL FARM2"
}
###


###
GET http://localhost:8080/api/cannacomply/FarmListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
   "id": "51b89fd6-830e-4a58-b153-02f9b41878a8"
}
###

###
POST http://localhost:8080/api/cannacomply/CreateCropService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "cropType": "CROP TYPE",
  "growthStage": "FLOWERING",
  "status": "planted",
  "strainName": "buddleCush",
  "seedCompany": "sensi seeds",
  "createdDate": "5-05-2023",
  "farmId": "",
  "userId": "",
  "cropLabel": "348923",
  "barcodeData": "[xxx]",
  "startingPlantData": "some staring data",
  "blockId": "234234234234324"


}
###

###
POST http://localhost:8080/api/cannacomply/UpdateCropService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "64a8899d-04e0-4ece-84d0-28c222e4ae2b",
  "cropType": "CROP TYPE",
  "blockLocation": "location2",
  "growthStage": "FLOWERING2",
  "status": "planted2",
  "strainName": "buddleCush2",
  "seedCompany": "sensi seeds2",
  "createdDate": "5-05-20232",
  "farmId": "2",
  "userId": "2",
  "cropLabel": "3489232",
  "barcodeData": "[xxx]2",
  "startingPlantData": "some staring data2"


}
###

###
GET http://localhost:8080/api/cannacomply/CropListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "7ae57d3d-a67c-4964-95e7-cad2b2e6b4b9"
}
###

POST http://localhost:8080/api/cannacomply/RegisterUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "firstName":"Dean",
  "lastName":"Richmond",
  "email":"juliusniki21aaa@gmail.com",
  "username":"juliusniki21aaa@gmail.com",
  "idnum": "1996",
  "roleId": "5",
  "contactNo": "3423423452"
}
###

POST http://localhost:8080/api/cannacomply/RegisterUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "firstName":"Dean",
  "lastName":"Richmond",
  "email":"juliusniki21aaa@gmail.com",
  "username":"juliusniki21aaa@gmail.com",
  "idnum": "1996",
  "roleId": "5",
  "contactNo": "3423423452"
}
###


POST http://localhost:8080/api/cannacomply/RegisterUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "firstName":"Dean",
  "lastName":"Richmond",
  "email":"juliusniki21aaa@gmail.com",
  "username":"juliusniki21aaa@gmail.com",
  "idnum": "1996",
  "roleId": "5",
  "contactNo": "3423423452"
}
###

POST http://localhost:8080/api/cannacomply/CreateActivityService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "cropId":"394857539487",
  "type":"Richmond",
  "activityData":"[{},{},{},{}]",
  "userId":"9872387987234",
  "farmId": "farm-id-2",
  "date": "04-05-2023",
  "status": "CREATED"
}
###

POST http://localhost:8080/api/cannacomply/UpdateActivityService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "971d7cef-fd9e-44e3-81dd-e036f6f15d31",
  "cropId":"394857539487-2",
  "type":"Richmond2",
  "activityData":"[{},{},{},{}]2",
  "userId":"9872387987234",
  "date": "04-05-2023",
  "status": "CREATED2"
}
###


GET http://localhost:8080/api/cannacomply/ActivityListService?activityId=971d7cef-fd9e-44e3-81dd-e036f6f15d31
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json
###

POST http://localhost:8080/api/cannacomply/CreateIssueService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "cropId":"394857539487",
  "title":"some title",
  "description":"some description",
  "severity":"4",
  "assignedTo": "dean richmond",
  "comment": "dome comments",
  "attachments": "file_data_",
  "farmId":"some-farm-id"
}
###

POST http://localhost:8080/api/cannacomply/UpdateIssueService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "f26dc7d1-3b60-41bb-98f9-86955ad4e6cd",
  "cropId":"394857539487",
  "title":"some title4",
  "description":"some description4",
  "severity":"4",
  "assignedTo": "dean richmond",
  "comment": "dome comments",
  "attachments": "file_data_",
  "farmId":"some-farm-id"
}
###


GET http://localhost:8080/api/cannacomply/IssueListService?id=f26dc7d1-3b60-41bb-98f9-86955ad4e6c
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json
###d

POST http://localhost:8080/api/cannacomply/CreateScheduleService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "farmId":"some-farm-id",
  "status":"some status",
  "startingDate":"01-12-2023",
  "endingDate":"01-01-2023",
  "title": "some title",
  "type": "some type",
  "assignedTo": "assigned to name",
  "description":"description"
}
###


GET http://localhost:8080/api/cannacomply/ScheduleListService?id=e5c4d870-9e53-45b7-884f-47ff499852f7
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json
###

###
POST http://localhost:8080/api/cannacomply/CreateBlockService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "blockLocation": "block location",
  "barcodeData": "[]",
  "farmId": "some-test-farm",
  "date": "12-12-2023"
}
###

GET http://localhost:8080/api/cannacomply/BlockListService?farmId=some-test-farm
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json
###




