
### dcd673bb-6f82-43c5-979c-df30da062562
POST https://cannacomply.connectmobiles24.com/api/oauth2/authorize
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Basic anVsaXVzQGNvbm5lY3Rtb2JpbGVzMjQuY29tOmRjZDY3M2JiLTZmODItNDNjNS05NzljLWRmMzBkYTA2MjU2Mg==
### API-ad757670-f1f8-4bcc-b879-3d511fbdc7b73


### user julius-niki = farmer role
POST https://cannacomply.connectmobiles24.com/api/cannacomply/CreateCropService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-049a21c8-382a-4557-a191-fc2a579108ee3
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "cropType": "dsfasdf",
  "blockId": null
}











###
GET https://cannacomply.connectmobiles24.com/api/cannacomply/ContractListService?farmId=43a506c4-21b4-49a4-8f0e-b9f8022a2a88
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-47d051aa-c4de-484d-83bd-081573b321f43
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a
###



###
GET https://cannacomply.connectmobiles24.com/api/cannacomply/BlogListService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-a218e752-4047-429f-9cbe-133eddf1df763
Content-Type: application/json
###

###
GET https://organicsimis.connectmobiles24.com/api/cannacomply/CropListService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-ad757670-f1f8-4bcc-b879-3d511fbdc7b73
Content-Type: application/json
###


GET https://cannacomply.connectmobiles24.com/api/cannacomply/BlockListService?farmId=d5ccb179-dea5-47da-b5bf-811f46da057e
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-ad757670-f1f8-4bcc-b879-3d511fbdc7b73
Content-Type: application/json
###


GET https://cannacomply.connectmobiles24.com/api/cannacomply/ActivityListService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-1276a41e-de9c-45ed-bd8c-5b482f864c4c3
Content-Type: application/json
###

GET https://organicsimis.connectmobiles24.com/api/cannacomply/CropDataListService
X-API-Key:e4e82dee-71e7-4773-86d4-1cb6dc1a2690
Authorization:Bearer API-7fb0c867-04ca-4859-b086-ea39cddd222029
Content-Type: application/json
Farm-id:596dc593-7ff4-4f2a-97bc-d12f35204a52

###

POST https://organicsimis.connectmobiles24.com/api/cannacomply/CreateFeedbackService
X-API-Key:e4e82dee-71e7-4773-86d4-1cb6dc1a2690
Authorization:Bearer API-d14c7379-7acb-49eb-9423-88f5d6c3b70f3
Content-Type: application/json
Farm-id:596dc593-7ff4-4f2a-97bc-d12f35204a52

{
  "farmId": "farm_id",
  "userId": "user_id",
  "comment": "comment",
  "date":"date"
}


###
GET https://organicsimis.connectmobiles24.com/api/cannacomply/CropListService
X-API-Key:e4e82dee-71e7-4773-86d4-1cb6dc1a2690
Authorization:Bearer API-7fb0c867-04ca-4859-b086-ea39cddd222029
Content-Type: application/json
Farm-id:596dc593-7ff4-4f2a-97bc-d12f35204a52

{
  "farmId": "farm_id",
  "userId": "user_id",
  "comment": "comment",
  "date":"date"
}


###

GET https://organicsimis.connectmobiles24.com/api/cannacomply/FeedbackListService?farmId=farm_id
X-API-Key:e4e82dee-71e7-4773-86d4-1cb6dc1a2690
Authorization:Bearer API-7fb0c867-04ca-4859-b086-ea39cddd222029
Content-Type: application/json
Farm-id:596dc593-7ff4-4f2a-97bc-d12f35204a52

###




###
POST https://cannacomply.connectmobiles24.com/api/cannacomply/UpdateSupplierService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-d4fb9a02-8e00-4f6b-92f2-f37b646c75e13
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "id": "9fc4dcd0-cd0b-487b-a9a5-c6e5df06b3ac",
  "farmId": "julius-nikiA23",
  "supplierName": "test supplier23",
  "productName": "test product23",
  "quantity": "20023",
  "expiryDate": "2022-12-12/23",
  "receipt":"test reciept3",
  "lotNumber": "lotNumber23",
  "container": "container23",
  "mass": "mass23"
}
###

POST https://cannacomply.connectmobiles24.com/api/cannacomply/UpdateIssueService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-172941e7-eb56-4bbd-9d13-e882f051e7a03
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "id": "3d0d7af2-1cca-409b-9491-6a14f778106f",
  "title":"some title4",
  "description":"some description53333333",
  "severity":"4",
  "assignedTo": "dean richmond",
  "itemType": "test",
  "comment": "dome comments",
  "attachments": "file_data_",
  "farmId":"some-farm-id"
}
###








###
POST https://cannacomply.connectmobiles24.com/api/cannacomply/UpdateUserService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-d4fb9a02-8e00-4f6b-92f2-f37b646c75e13
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "uniqueId": "9fc4dcd0-cd0b-487b-a9a5-c6e5df06b3ac",
  "userType": "something2"

}
###

###
GET https://cannacomply.connectmobiles24.com/api/cannacomply/CropListService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-f82c7f27-e5eb-4218-8213-21fe9d4d019d3
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "uniqueId": "9fc4dcd0-cd0b-487b-a9a5-c6e5df06b3ac",
  "userType": "something2"

}
###



POST https://cannacomply.connectmobiles24.com/api/cannacomply/CreateCustomerService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-d4fb9a02-8e00-4f6b-92f2-f37b646c75e13
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "customerName": "customerName",
  "country": "country",
  "city": "city",
  "contactNo": "contactNo",
  "email": "email",
  "farmId": "farmId",
  "address": "address"
}
###

POST https://cannacomply.connectmobiles24.com/api/cannacomply/UpdateCustomerService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-d4fb9a02-8e00-4f6b-92f2-f37b646c75e13
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "id": "19ae8b77-1551-4098-810e-d49d20ec4fef",
  "customerName": "customerName2"
}
###

GET https://cannacomply.connectmobiles24.com/api/cannacomply/TreatmentProductListService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-6c953258-7039-45ca-9ab3-4749d92d289d3
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "farm_id": "2ca8f7ca-dc16-49c3-af2c-49bbb7d1eb65"
}
###



###
GET http://localhost:8080/api/cannacomply/CustomerListService?famrId=farmId
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f45c1133-3a5e-4b56-88fa-075da5e13a2f1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###
GET https://cannacomply.connectmobiles24.com/api/cannacomply/ContractListService?farmId=27eca4ed-b247-4fbb-ab60-3834101116ed
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-78b5502e-2c4a-4ac6-8ae0-52099f4c6bb93
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

###
POST https://cannacomply.connectmobiles24.com/api/cannacomply/CreateHygieneService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-78b5502e-2c4a-4ac6-8ae0-52099f4c6bb93
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "farmId": "farmId",
  "locationId": "locationId",
  "date": "date",
  "type": "type",
  "form": "form",
  "userId": "userId"
}

###
GET https://cannacomply.connectmobiles24.com/api/cannacomply/GetPowerBiAuthTokenService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-78b5502e-2c4a-4ac6-8ae0-52099f4c6bb93
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a
###