
###
POST http://localhost:8080/api/oauth2/authorize
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Basic YWRtaW4xNjY1MTQ1MTgzNzQ2OmRjZDY3M2JiLTZmODItNDNjNS05NzljLWRmMzBkYTA2MjU2Mg==
###


###
POST http://localhost:8080/api/cannacomply/CreateFarmService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "name": "New test farm",
  "latitude": "23.4543",
  "longitude": "-33.4432",
  "logoData": "year",
  "type": "NORMAL FARM"
}
###

POST http://localhost:8080/api/cannacomply/CreateYieldService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-957e93dc-30e9-4511-a3d6-3e95f0cd0f151
Content-Type: application/json

{
  "quantity": "300",
  "loss": "12",
  "notes": "some notes",
  "harvestBatchId": "234234234",
  "farmId": "23423456",
  "location": "Location",
  "cropId": "543452453245",
  "strain": "Madusas magic",
  "date": "11112332"
}
###

###
GET http://localhost:8080/api/cannacomply/YieldListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-957e93dc-30e9-4511-a3d6-3e95f0cd0f151
Content-Type: application/json
###

###
GET http://localhost:8080/api/cannacomply/BlogListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6774641f-2ad2-4d30-be0e-ea281b88a7ff1
Content-Type: application/json
###

###
GET http://localhost:8080/api/cannacomply/UserListService?uniqueId=julius-niki
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-5960348c-76b2-49ff-8c14-b6f1bc87391c1
Content-Type: application/json
###

###
GET http://localhost:8080/api/cannacomply/UserListService?farmId=farm_id
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-5960348c-76b2-49ff-8c14-b6f1bc87391c1
Content-Type: application/json
###



GET http://localhost:8080/api/cannacomply/YieldListService?cropId=543452453245
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-957e93dc-30e9-4511-a3d6-3e95f0cd0f151
Content-Type: application/json
###

GET http://localhost:8080/api/cannacomply/YieldListService?yieldId=543452453245
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-957e93dc-30e9-4511-a3d6-3e95f0cd0f151
Content-Type: application/json
###


POST http://localhost:8080/api/cannacomply/UpdateFarmService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "c96f40ee-d211-4075-8d37-635febe1e3f4",
  "name": "New test farm2",
  "latitude": "23.4543-2",
  "longitude": "-33.4432-2",
  "logoData": "year2",
  "type": "NORMAL FARM2"
}
###


###
GET http://localhost:8080/api/cannacomply/FarmListService?userId=julius-niki2
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
   "id": "51b89fd6-830e-4a58-b153-02f9b41878a8"
}
###

###
POST http://localhost:8080/api/cannacomply/CreateTreatmentProductService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

{
  "productName": "testProduct",
  "container": "container",
  "mass": "100",
  "quantity": "100",
  "farmId": "12345667",
  "productId": "5-05-2023",
  "activeIngredients": "",
  "expiryDate": "12-12-2020",
  "instructions": "[xxx]",
  "purpose": "some data"

}
###

###
POST http://localhost:8080/api/cannacomply/CreateComplianceUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

{
  "sysUniqueUserId": "julius-niki",
  "farmId": "c96f40ee-d211-4075-8d37-635febe1e3f4",
  "userRole": "FARMER_ADMIN"
}
###

###
POST http://localhost:8080/api/cannacomply/CreatePackageService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

{
  "packageTag": "some tag",
  "item": "item",
  "quantity": "300",
  "farmId": "34234234",
  "location": "Location",
  "status": "SOME STATUS",
  "date": "date",
  "harvestId": "harvestId"
}
###

###
POST http://localhost:8080/api/cannacomply/UpdatePackagingService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

{
  "id": "c6ce8140-bb1e-41b0-ae52-32a4419e2091",
  "packageTag": "some tag",
  "item": "item",
  "quantity": "300",
  "farmId": "34234234",
  "location": "location2",
  "status": "SOME STATUS2",
  "date": "date2",
  "harvestId": "harvestId"
}





###
GET http://localhost:8080/api/cannacomply/PackagingListService?id=c6ce8140-bb1e-41b0-ae52-32a4419e2091
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

###

###
GET http://localhost:8080/api/cannacomply/PackagingListService?farmId=c6ce8140-bb1e-41b0-ae52-32a4419e2091
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

###

###
GET http://localhost:8080/api/cannacomply/SupplierListService?farmId=julius-nikiA
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

###




###
POST http://localhost:8080/api/cannacomply/UpdateComplianceUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-a281f024-a26e-4d16-8dfb-5ca8943fe70c1
Content-Type: application/json

{
  "uuid": "67f8be5d-6b9c-4beb-a6a3-78fd2d2145dd",
  "sysUniqueUserId": "julius-nikiA",
  "farmId": "c96f40ee-d211-4075-8d37-635febe1e3f4A",
  "userRole": "FARMER_ADMINA"
}
###

###
POST http://localhost:8080/api/cannacomply/CreateSupplierService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

{
  "farmId": "julius-nikiA",
  "supplierName": "test supplier",
  "productName": "test product",
  "quantity": "200",
  "expiryDate": "2022-12-12",
  "receipt":"test reciept",
  "lotNumber": "lotNumber",
  "container": "container",
  "mass": "mass"
}
###

###
POST http://localhost:8080/api/cannacomply/CreateReadingService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-5e499090-49bf-4021-bcf8-af4477eeb32c1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "temp": "22.6",
  "ph": "6",
  "humidity": "75",
  "roomId": "sdfgsdfgeertwert"
}

###
POST http://localhost:8080/api/cannacomply/UpdateSupplierService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f45c1133-3a5e-4b56-88fa-075da5e13a2f1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "id": "929a6128-685f-4535-9a1b-78cb1d6b4d36",
  "farmId": "julius-nikiA2",
  "supplierName": "test supplier2",
  "productName": "test product2",
  "quantity": "2002",
  "expiryDate": "2022-12-12/2",
  "receipt":"test reciept",
  "lotNumber": "lotNumber2",
  "container": "container2",
  "mass": "mass2"
}
###

###
POST http://localhost:8080/api/cannacomply/CreateGrowthCycleService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f45c1133-3a5e-4b56-88fa-075da5e13a2f1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "plants": "julius-nikiA2",
  "startDate": "test supplier2",
  "endDate": "test product2",
  "strain": "2002",
  "farmId": "2022-12-12/2"
}
###

###
POST http://localhost:8080/api/cannacomply/CreateContractService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f45c1133-3a5e-4b56-88fa-075da5e13a2f1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "strain": "strain",
  "customerId": "customerId",
  "farmId": "farmId",
  "deliveryDate": "deiveryDate",
  "type": "type",
  "price": "price",
  "quantity": "quantity",
  "contractDate": "contractDate",
  "growthCycleId": "gorwthCycleId"
}
###

POST http://localhost:8080/api/cannacomply/CreateCustomerService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f45c1133-3a5e-4b56-88fa-075da5e13a2f1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "customerName": "customerName",
  "country": "country",
  "city": "city",
  "contactNo": "contactNo",
  "email": "email",
  "farmId": "farmId",
  "address": "address"
}
###
GET http://localhost:8080/api/cannacomply/CustomerListService?famrId=farmId
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f45c1133-3a5e-4b56-88fa-075da5e13a2f1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###
GET http://localhost:8080/api/cannacomply/ContractListService?famrId=27eca4ed-b247-4fbb-ab60-3834101116ed
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f45c1133-3a5e-4b56-88fa-075da5e13a2f1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4



###
GET http://localhost:8080/api/cannacomply/GrowthCycleListService?farmId=awerqwerqwer
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f45c1133-3a5e-4b56-88fa-075da5e13a2f1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4




###
GET http://localhost:8080/api/cannacomply/ReadingListService?id=aaab52a8-5d75-49d6-b8dc-1565b8b9388e
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###

###
GET http://localhost:8080/api/cannacomply/CalculateAverageForReadingsService?readingType=temperature&locationId=234234&farmId=3242324
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4java -version

###

###
GET http://localhost:8080/api/cannacomply/UserUploadListService?farmId=33
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###

###
POST http://localhost:8080/api/cannacomply/DeleteUserUploadService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-ccdde073-e4f6-4c20-b3cb-65b178c39a381
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "uploadId": "0fdba811-4b06-45ec-98ed-27843b8f3f55"
}

###




###
GET http://localhost:8080/api/cannacomply/DeviceListService?farmId=3242324
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###

###
GET http://localhost:8080/api/cannacomply/DeviceListService?deviceId=78f43f95-6f1c-4c07-8ffb-499a2b415f85
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###

###
GET http://localhost:8080/api/cannacomply/DeviceListService?locationId=234234
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###



###
POST http://localhost:8080/api/cannacomply/CreateReadingService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{ "date": "12-12-2023",
  "deviceId": "234234",
  "readingType": "Temp",
  "readingValue": "23.3",
  "status": "test",
  "farmId": "3242324",
  "actionTaken": "none",
  "userId": "234234"
}

###

POST http://localhost:8080/api/cannacomply/CreateDeviceService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{ "deviceType": "Thermometer",
  "locationType": "Location",
  "locationId": "234234",
  "date": "12-12-2023",
  "status": "testing",
  "farmId": "3242324",
  "usage": "none",
  "lastUpdated": "12-12-2021"
}

###


###
GET http://localhost:8080/api/cannacomply/ReadingListService?deviceId=234234
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###

GET http://localhost:8080/api/cannacomply/ReadingListService?readingId=3e7f6250-4ba7-4f5e-815a-7059e37719a7
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f8bdd97e-4f62-4af4-9f36-bdbf05a9f5f61
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###


GET http://localhost:8080/api/cannacomply/ComplianceUserListService?id=aaab52a8-5d75-49d6-b8dc-1565b8b9388e
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4
###

###
GET http://localhost:8080/api/cannacomply/ComplianceUserListService?farmId=c96f40ee-d211-4075-8d37-635febe1e3f4A
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

###

GET http://localhost:8080/api/cannacomply/ComplianceUserListService?sysUniqueUserId=conway-buck
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

###

GET http://localhost:8080/api/cannacomply/TreatmentProductListService?farmId=12345667
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

###
###
GET http://localhost:8080/api/cannacomply/TreatmentProductListService?productId=5-05-2023
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-bb308df9-83a7-4f8c-967b-b577fcce39681
Content-Type: application/json

###


###
POST http://localhost:8080/api/cannacomply/UpdateCropService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "64a8899d-04e0-4ece-84d0-28c222e4ae2b",
  "cropType": "CROP TYPE",
  "blockLocation": "location2",
  "growthStage": "FLOWERING2",
  "status": "planted2",
  "strainName": "buddleCush2",
  "seedCompany": "sensi seeds2",
  "createdDate": "5-05-20232",
  "farmId": "2",
  "userId": "2",
  "cropLabel": "3489232",
  "barcodeData": "[xxx]2",
  "startingPlantData": "some staring data2"


}
###

###
GET http://localhost:8080/api/cannacomply/CropListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "7ae57d3d-a67c-4964-95e7-cad2b2e6b4b9"
}
###

POST http://localhost:8080/api/cannacomply/RegisterComplianceUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-653a20bf-a97c-458f-828b-ccbf4c49766e1
Content-Type: application/json

{
  "firstName":"Dean",
  "lastName":"Richmond",
  "email":"juliusniki21aaa1111111@gmail.com",
  "username":"juliusniki21aaa1111111@gmail.com",
  "idnum": "1996",
  "roleId": "5",
  "contactNo": "3423423452",
  "farmId": "farm_id",
  "userRole": "user_role"
}
###

POST http://localhost:8080/api/cannacomply/RegisterUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "firstName":"Dean",
  "lastName":"Richmond",
  "email":"juliusniki21aaa@gmail.com",
  "username":"juliusniki21aaa@gmail.com",
  "idnum": "1996",
  "roleId": "5",
  "contactNo": "3423423452"
}
###


POST http://localhost:8080/api/cannacomply/RegisterUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "firstName":"Dean",
  "lastName":"Richmond",
  "email":"juliusniki21aaa@gmail.com",
  "username":"juliusniki21aaa@gmail.com",
  "idnum": "1996",
  "roleId": "5",
  "contactNo": "3423423452"
}
###

POST http://localhost:8080/api/cannacomply/CreateActivityService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-4d25debc-4016-45c1-aced-2aa9c69e2a8a1
Content-Type: application/json
Farm-id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "cropId":"394857539487",
  "type":"Richmond",
  "activityData":"[{},{},{},{}]",
  "userId":"9872387987234",
  "farmId": "farm-id-2",
  "date": "04-05-2023",
  "status": "CREATED"
}
###

POST http://localhost:8080/api/cannacomply/UpdateActivityService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-4d25debc-4016-45c1-aced-2aa9c69e2a8a1
Content-Type: application/json
Farm-id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "id": "971d7cef-fd9e-44e3-81dd-e036f6f15d31",
  "cropId":"394857539487-2",
  "type":"Richmond2",
  "activityData":"[{},{},{},{}]2",
  "userId":"9872387987234",
  "date": "04-05-2023",
  "status": "CREATED2"
}
###


GET http://localhost:8080/api/cannacomply/ActivityListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-4d25debc-4016-45c1-aced-2aa9c69e2a8a1
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4
###

POST http://localhost:8080/api/cannacomply/CreateIssueService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-df90c02d-5159-4d4d-8bc3-fc9e509b9af91
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "cropId":"394857539487",
  "title":"some title",
  "description":"some description",
  "severity":"4",
  "assignedTo": "dean richmond",
  "comment": "dome comments",
  "attachments": "file_data_",
  "farmId":"some-farm-id",
  "dueDate": "due_date",
  "solution": "solution",
  "status": "status"
}
###

POST http://localhost:8080/api/cannacomply/UpdateIssueService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-825ed5d7-e981-42c7-b879-de1701c301031
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "id": "79e022c8-a095-469a-bde6-6aa3688d3db9",
  "title":"some title4",
  "description":"some description53333333",
  "severity":"4",
  "assignedTo": "dean richmond",
  "comment": "dome comments",
  "attachments": "file_data_",
  "farmId":"some-farm-id"
}
###

POST http://localhost:8080/api/cannacomply/CreateSoilManagementService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-825ed5d7-e981-42c7-b879-de1701c301031
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "texture":"texture",
  "ph": "ph",
  "farmId":"farmId",
  "date": "date",
  "nutrientLevels":"nutrientLevels",
  "soilType": "soilType",
  "locationId": "locationId",
  "locationType": "locationType",
  "warehouseItemId": "warehouseItemId",
  "organicMatter": "organicMatter"
}
###

POST http://localhost:8080/api/cannacomply/CreateWaterManagementService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-825ed5d7-e981-42c7-b879-de1701c301031
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "userId": "UserId",
  "locationId": "locationId",
  "locationType": "locationType",
  "waterUse": "waterUse",
  "farmId": "farmId",
  "waterSourceId": "waterSourceId",
  "startTime": "startTime",
  "endTime": "endTIme",
  "methodUsed": "methodUsed",
  "flowRate": "flowRate",
  "waterQuantity": "waterQty",
  "waterUnitsUsed": "waterUnitsUsed",
  "waterTemp": "waterTemp",
  "waterPh": "waterPh",
  "rateUnit": "rateUnit",
  "date": "date",
  "ppmLevels": "ppm_levels",
  "deviceId": "deviceId"
}
###

POST http://localhost:8080/api/cannacomply/CreateWaterSourceService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-825ed5d7-e981-42c7-b879-de1701c301031
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "name": "name2",
  "optimalReadingsJson": "optimal_readings_json",
  "farmId": "farm_id",
  "date": "date",
  "type": "type",
  "volume": "volume",
  "usage": "usage",
  "geoData": "geoData",
  "colour": "colour",
  "units": "units"
}
###

GET http://localhost:8080/api/cannacomply/WaterSourceListService?farmId=farm_id
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-825ed5d7-e981-42c7-b879-de1701c301031
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###

GET https://cannacomply.connectmobiles24.com/api/cannacomply/WaterSourceListService?id=e4136f48-9ed8-4a22-9e95-bf36b0ef9c34
X-API-Key:705a97c3-87f6-44f9-b395-832fafe890ac
Authorization:Bearer API-35d2091f-f053-404f-85a2-16c68a8aeab329
Content-Type: application/json
Farm-Id:596dc593-7ff4-4f2a-97bc-d12f35204a52

###




GET http://localhost:8080/api/cannacomply/WaterManagementListService?farmId=farmId
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-825ed5d7-e981-42c7-b879-de1701c301031
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

###




POST http://localhost:8080/api/cannacomply/CreateSoilPotService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-825ed5d7-e981-42c7-b879-de1701c301031
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "soilId":"soilId",
  "quantity": "quantity",
  "farmId":"farmId",
  "date": "date",
  "measurements":"measurements",
  "status": "status",
  "locationId": "locationId",
  "locationType": "locationType",
  "containerType": "containerType"
}
###






POST http://localhost:8080/api/cannacomply/UpdateUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "id": "f26dc7d1-3b60-41bb-98f9-86955ad4e6cd",
  "cropId":"394857539487",
  "title":"some title4",
  "description":"some description4",
  "severity":"4",
  "assignedTo": "dean richmond",
  "comment": "dome comments",
  "attachments": "file_data_",
  "farmId":"some-farm-id"
}
###




GET http://localhost:8080/api/cannacomply/IssueListService?id=f26dc7d1-3b60-41bb-98f9-86955ad4e6c
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json
###d

POST http://localhost:8080/api/cannacomply/CreateScheduleService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "farmId":"some-farm-id",
  "status":"some status",
  "startingDate":"01-12-2023",
  "endingDate":"01-01-2023",
  "title": "some title",
  "type": "some type",
  "assignedTo": "assigned to name",
  "description":"description"
}
###


GET http://localhost:8080/api/cannacomply/ScheduleListService?id=e5c4d870-9e53-45b7-884f-47ff499852f7
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json
###

###
POST http://localhost:8080/api/cannacomply/CreateBlockService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "blockLocation": "block Location",
  "barcodeData": "[]",
  "farmId": "some-test-farm",
  "date": "12-12-2023"
}
###

GET http://localhost:8080/api/cannacomply/BlockListService?farmId=some-test-farm
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json
###

POST http://localhost:8080/api/cannacomply/RegisterUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-cd246e7b-e4c3-4942-8caa-4cc490f1356e1
Content-Type: application/json

{
  "firstName":"Dean",
  "lastName":"Richmond",
  "email":"juliusniki953@gmail.com",
  "username":"juliusniki953@gmail.com",
  "idnum": "1996",
  "roleId": "5",
  "contactNo": "3423423452"
}
###


###
POST http://localhost:8080/api/cannacomply/CreateRoomService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-ed8f0b3b-bb31-43fd-80d4-e7c5c4375e201
Content-Type: application/json

{
  "roomName": "Test Location 1",
  "roomDescription": "some amazing Location for curing ",
  "locationData": "[{},{}]",
  "farmId": "29384792837483",
  "roomColour": "green"
}
###


GET http://localhost:8080/api/cannacomply/RoomListService?farmId=29384792837483
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-ed8f0b3b-bb31-43fd-80d4-e7c5c4375e201
Content-Type: application/json
###

GET http://localhost:8080/api/cannacomply/RoomListService?id=5384f4aa-1992-4f7b-b057-0cd955816b1f
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-ed8f0b3b-bb31-43fd-80d4-e7c5c4375e201
Content-Type: application/json
###

###
POST http://localhost:8080/api/cannacomply/UpdateUserService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-fb3efb23-0928-4acf-b895-2a2e3b92ec931
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "uniqueId": "test-t-16",
  "userType": "something2"

}
###


###
POST http://localhost:8080/api/cannacomply/UpdateApiAccessService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-fb3efb23-0928-4acf-b895-2a2e3b92ec931
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "uniqueId": "test-t-16",
  "userType": "something2"

}
###

###
GET http://localhost:8080/api/cannacomply/ApiAccessListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-fb3efb23-0928-4acf-b895-2a2e3b92ec931
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
}
###

###
GET http://localhost:8080/api/cannacomply/StrainListService?type=indica/sativa
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-dd6b62df-6bbf-4486-be79-17ac65ca67301
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4
###

###
GET http://localhost:8080/api/cannacomply/GetPowerBiAuthTokenService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-dd6b62df-6bbf-4486-be79-17ac65ca67301
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4
###

###
POST http://localhost:8080/api/cannacomply/CreateWaterManagementService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-dd6b62df-6bbf-4486-be79-17ac65ca67301
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4

{
  "userId": "userId",
  "locationId": "locatiohId",
  "locationType": "locationType",
  "waterUse": "water use",
  "farmId": "farm id",
  "waterSource": "water source",
  "startTime": "start time",
  "endTime": "end time",
  "methodUsed": "method_used",
  "flowRate" : "flow rate",
  "waterQuantity": "water quantrity",
  "waterUnitsUsed": "units used",
  "waterTemp": "water tempo",
  "waterPh": "water ph",
  "rateUnit": "rate uunit",
  "date": "date"

}

###
GET http://localhost:8080/api/cannacomply/WaterManagementListService?farmId=farm_id
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-dd6b62df-6bbf-4486-be79-17ac65ca67301
Content-Type: application/json
Farm-Id:c96f40ee-d211-4075-8d37-635febe1e3f4









