
###
POST https://carfix.connectmobiles24.com/api/oauth2/authorize
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Basic anVsaXVzQGNvbm5lY3Rtb2JpbGVzMjQuY29tOjEyMzQ1Njc4
###





POST https://carfix.connectmobiles24.com/api/carfix/CreateVehicleService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization: Bearer API-81b09a03-9dca-4a27-8df8-01d545c344af5
Content-Type: application/json

{
  "vinNumber": "23432666456",
  "registration": "G3344d GP",
  "make": "Mercedes",
  "model": "year",
  "year": "2002",
  "fuelType": "petrol",
  "transmission": "manual",
  "odoReading": "2340333",
  "engineCode": "3043",
  "memberId": "julius-niki"
}
###


POST https://carfix.connectmobiles24.com/api/carfix/CreateQuoteService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization: Bearer API-c7525b1f-2467-4edf-912f-36af613e17fc5
Content-Type: application/json

{
  "requestForServiceId":"2343243254",
  "serviceProviderId":"234234543",
  "serviceProviderName": "TEST DATA",
  "quotationItems":[
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    }
  ]
}
###


###
GET https://carfix.connectmobiles24.com/api/carfix/QuoteListService?serviceProviderId=234234543
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization: Bearer API-c7b60543-654c-4a28-b773-1acc5c492ab25

###


POST https://carfix.connectmobiles24.com/api/carfix/AcceptQuoteService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-ec51cb2c-3b31-4f83-ab7d-5ffbbc2b40e55
Content-Type: application/json

{
  "serviceRequestId": "303a67af-f8da-4030-9144 -90c56bfc3caf",
  "acceptedQuoteId": "bbe4c739-9745-4243-8d7f-475fc5045722",
  "confirmedServiceProviderId":"bbf4c739-9745-4243-8d7f-475fc5045726"
}


###
GET https://carfix.connectmobiles24.com/api/carfix/RFSListService?memberId=romeo-williams
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-f97ea9ee-4219-4f37-85c9-fd9dbb800d5b5
###

###
GET https://carfix.connectmobiles24.com/api/carfix/RFSListService?serviceProviderUniqueId=autohaul-workshop-autohaul-workshop-4
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-5da33a5a-6975-4186-83a7-6b7e92a393155
###



POST https://carfix.connectmobiles24.com/api/carfix/CreateRFSService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-3634edfb-50af-41dc-8ea2-53a14027bd8e5
Content-Type: application/json

{
  "type": "REQUEST_FOR_SERVICE",
  "vehicleId": "4333e22",
  "memberId": "334423",
  "radius": "10 KM",
  "status": "CREATED",
  "currentOdoReading": "234233.00",
  "pictureData": "base64Ecode(some data)",
  "additionalDescription": "need to change shocks",
  "lastServiceDate": "10-10-2021",
  "vehicleBrandId": "1dde16fc-bb78-41ec-bae0-7c6c9b4ba5ac",
  "serviceRequestItems": [{"itemCategoryId": "6ea8bc58-e17d-48c7-9ef7-d6746e6a9b33","itemDescription": "front shocks"},{"itemCategoryId": "6ea8bc58-e17d-48c7-9ef7-d6746e6a8b70","itemDescription": "rear shocks"}],
  "preferredDate": "1676641315237"
}
###

###
GET https://carfix.connectmobiles24.com/api/carfix/ServiceProviderListService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-3c289184-e690-4ac7-bdb3-32cff6d209665
###

###
GET https://carfix.connectmobiles24.com/api/carfix/ServiceProviderListService?id=de6e124f-e7c4-4882-af27-41ebd375a9cc
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-3c289184-e690-4ac7-bdb3-32cff6d209665


###
POST https://carfix.connectmobiles24.com/api/carfix/RegisterMemberService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-3c289184-e690-4ac7-bdb3-32cff6d209665
Content-Type: application/json

{
"firstName":"Test",
"lastName":"T",
"email":"julius6366566@test.com",
"username":"julius66365663@test.com",
"idnum": "1996",
"roleId": "5"
}
###

POST https://carfix.connectmobiles24.com/api/carfix/RegisterServiceProviderService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-3c289184-e690-4ac7-bdb3-32cff6d209665
Content-Type: application/json

{
  "firstName":"Test",
  "lastName":"T",
  "email":"nwesp22@test.com",
  "username":"nwesp22@test.com",
  "idnum": "1996",
  "roleId": "5",
  "certifications": "certifications format?",
  "userType": "SERVICE_PROVIDER",
  "supportedBrands": [{"id": "1dde16fc-bb78-41ec-bae0-7c6c9b4ba5ac"}],
  "supportedCategories": [{"id": "6ea8bc58-e17d-48c7-9ef7-d6746e6a9b33"},{"id": "6ea8bc58-e17d-48c7-9ef7-d6746e6a8b70"}],
  "name": "SomeAmazingServiceProvider",
  "address": "1 Lobelia close bellville 7540",
  "aboutUs": "some information about the SP",
  "logoData": "encoded_logo_data",
  "contactNo": "3423423452"
}
###

###
GET https://carfix.connectmobiles24.com/api/carfix/RFSListService?serviceProviderId=e05dc5d2-dd69-495f-98c5-066754a9b9c7
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-3c289184-e690-4ac7-bdb3-32cff6d209665
###


