
###
POST https://carfix.connectmobiles24.com/api/oauth2/authorize
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Basic anVsaXVzQGNvbm5lY3Rtb2JpbGVzMjQuY29tOjEyMzQ1Njc4
###


###
POST https://carfix.connectmobiles24.com/api/carfix/ProcessServiceProvidersPayments
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-ac4ee3cb-ba87-46eb-93b8-53976d76297d5
Content-Type: application/json
###





POST https://carfix.connectmobiles24.com/api/carfix/CreateVehicleService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization: Bearer API-261e9b38-22d3-4496-8cf2-a69c735987585
Content-Type: application/json

{
  "vinNumber": "23432666456",
  "registration": "G3344d GP",
  "make": "Mercedes",
  "model": "year",
  "year": "2002",
  "fuelType": "petrol",
  "transmission": "manual",
  "odoReading": "2340333",
  "engineCode": "3043",
  "memberId": "julius-niki"
}
###


POST https://carfix.connectmobiles24.com/api/carfix/CreateQuoteService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization: Bearer API-c7525b1f-2467-4edf-912f-36af613e17fc5
Content-Type: application/json

{
  "requestForServiceId":"2343243254",
  "serviceProviderId":"234234543",
  "serviceProviderName": "TEST DATA",
  "quotationItems":[
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    }
  ]
}
###


###
GET https://carfix.connectmobiles24.com/api/carfix/QuoteListService?requestForServiceId=a4c3ae5b-8ea4-4eb5-9c5f-4a818ed9eb97
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization: Bearer API-d9216bcf-b3d5-4f33-8276-25b13dc9ae145

###


POST https://carfix.connectmobiles24.com/api/carfix/AcceptQuoteService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-ec51cb2c-3b31-4f83-ab7d-5ffbbc2b40e55
Content-Type: application/json

{
  "serviceRequestId": "303a67af-f8da-4030-9144 -90c56bfc3caf",
  "acceptedQuoteId": "bbe4c739-9745-4243-8d7f-475fc5045722",
  "confirmedServiceProviderId":"bbf4c739-9745-4243-8d7f-475fc5045726"
}


###
GET https://carfix.connectmobiles24.com/api/carfix/RFSListService?memberId=romeo-williams
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-f97ea9ee-4219-4f37-85c9-fd9dbb800d5b5
###

###
GET https://carfix.connectmobiles24.com/api/carfix/RFSListService?serviceProviderUniqueId=0190604c-da39-4aa0-89b4-3d099732217d
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-93464062-39e1-46cd-92af-2600c75d0d715
###



OPTIONS https://carfix.connectmobiles24.com/api/carfix/CreateRFSService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-fb8381c3-1ca0-44e4-9a7d-0b70d0267d285
Content-Type: application/json

{
  "type": "REQUEST_FOR_SERVICE",
  "vehicleId": "4333e22",
  "memberId": "334423",
  "radius": "10 KM",
  "status": "CREATED",
  "currentOdoReading": "234233.00",
  "pictureData": "base64Ecode(some data)",
  "additionalDescription": "need to change shocks",
  "lastServiceDate": "10-10-2021",
  "vehicleBrandId": "1dde16fc-bb78-41ec-bae0-7c6c9b4ba5ac",
  "serviceRequestItems": [{"itemCategoryId": "6ea8bc58-e17d-48c7-9ef7-d6746e6a9b33","itemDescription": "front shocks"},{"itemCategoryId": "6ea8bc58-e17d-48c7-9ef7-d6746e6a8b70","itemDescription": "rear shocks"}],
  "preferredDate": "1676641315237"
}
###

###
GET https://carfix.connectmobiles24.com/api/carfix/ServiceProviderListService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-e67f8489-b0fc-4f7a-b545-b6be75419a8a5
Content-Type: application/json
###

###
GET https://carfix.connectmobiles24.com/api/carfix/ServiceProviderListService?serviceProviderUniqueId=steves-auto-workshop-steves-auto-workshop
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-93464062-39e1-46cd-92af-2600c75d0d715



###
POST https://carfix.connectmobiles24.com/api/carfix/RegisterMemberService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-93464062-39e1-46cd-92af-2600c75d0d715
Content-Type: application/json

{
"firstName":"Julius",
"lastName":"Nikitaridis",
"email":"juliusniki@gmail.com",
"username":"juliusniki@gmail.com",
"idnum": "8712225152088",
"roleId": "5"
}
###

POST https://carfix.connectmobiles24.com/api/carfix/UpdateServiceProviderService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-93464062-39e1-46cd-92af-2600c75d0d715
Content-Type: application/json

{
  "serviceProviderId": "3f5efcf8-eced-4d1a-8b38-f9df3790328f",
  "operatingHours": "{none}",
  "aboutUs": "something new 2"
}
###
POST https://carfix.connectmobiles24.com/api/carfix/RegisterMemberService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-93464062-39e1-46cd-92af-2600c75d0d715
Content-Type: application/json

{
  "firstName":"Test",
  "lastName":"T",
  "email":"juliusniki2@gmail.com",
  "username":"juliusniki2@gmail.com",
  "idnum": "8712225152088",
  "roleId": "5"
}
###

POST https://carfix.connectmobiles24.com/api/carfix/RegisterServiceProviderService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-bc51c982-f001-4d75-b361-dee3899544cf5
Content-Type: application/json

{
  "firstName":"Test",
  "lastName":"T",
  "email":"nwesp22@test.com",
  "username":"nwesp22@test.com",
  "idnum": "1996",
  "roleId": "5",
  "certifications": "certifications format?",
  "userType": "SERVICE_PROVIDER",
  "supportedBrands": [{"id": "1dde16fc-bb78-41ec-bae0-7c6c9b4ba5ac"}],
  "supportedCategories": [{"id": "6ea8bc58-e17d-48c7-9ef7-d6746e6a9b33"},{"id": "6ea8bc58-e17d-48c7-9ef7-d6746e6a8b70"}],
  "name": "SomeAmazingServiceProvider",
  "address": "1 Lobelia close bellville 7540",
  "aboutUs": "some information about the SP",
  "logoData": "encoded_logo_data",
  "contactNo": "3423423452",
  "operatingHours":"{}"
}
###

###
GET https://carfix.connectmobiles24.com/api/carfix/RFSListService?serviceProviderId=31e76905-c770-48e2-95e2-c79c17475212
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-d765b107-4cd0-476e-abc1-e578e06c5d035
###

POST https://carfix.connectmobiles24.com/api/carfix/UpdateServiceRequestService
X-API-Key:2ada9fbb-4478-4733-bb10-b96119c6c695
Authorization:Bearer API-d0c34c1e-d993-4aa2-b15a-c6e1ee525d3c5
Content-Type: application/json

{
  "id": "0b927ba6-f1aa-4ada-856d-ff9ae95750d3",
  "confirmedDate": "12-12-2024",
  "preferredDate": "12-12-2024"
}
###


