
###
POST http://localhost:8080/api/oauth2/authorize
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Basic YWRtaW4xNjY1MTQ1MTgzNzQ2OmRjZDY3M2JiLTZmODItNDNjNS05NzljLWRmMzBkYTA2MjU2Mg==
###


GET http://localhost:8080/api/carfix/VehicleListService?vehicleId=224d68f0-2629-430e-833e-215a54cb702c
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###



##
GET http://localhost:8080/api/carfix/VehicleListService?memberId=julius-niki
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###



POST http://localhost:8080/api/carfix/CreateVehicleService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-79c396c1-b96c-4cc0-a321-74f00e5715c91
Content-Type: application/json

{
  "vinNumber": "23432666456",
  "registration": "G3344d GP",
  "make": "Mercedes",
  "model": "year",
  "year": "2002",
  "fuelType": "petrol",
  "transmission": "manual",
  "odoReading": "2340333",
  "engineCode": "3043",
  "memberId": "julius-niki"
}
###




POST http://localhost:8080/api/carfix/CreateRFSService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-a9a46150-a2a0-425a-9a9c-317e2ed3f2121
Content-Type: application/json

{
  "date": "12-12-2022",
  "type": "REQUEST_FOR_SERVICE",
  "vehicleId": "4333e",
  "memberId": "334423",
  "radius": "10 KM",
  "status": "CREATED",
  "currentOdoReading": "234233.00",
  "pictureData": "base64Ecode(some data)",
  "additionalDescription": "need to change shocks",
  "lastServiceDate": "10-10-2021",
  "serviceRequestItems": [{"serviceRequestOptionId": "34234234"},{"serviceRequestOptionId": "34234111"},{"serviceRequestOptionId": "34235554"}]
}
###

###
GET http://localhost:8080/api/carfix/RFSListService?memberId=334423
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-3f4f5866-3f7a-443b-94d7-29f2c6d032a11
###

###
GET http://localhost:8080/api/carfix/RFSListService?vehicleId=4333e
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###


###
GET http://localhost:8080/api/carfix/RFSListService?serviceRequestId=303a67af-f8da-4030-9144-90c56bfc3caf
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###

###
GET http://localhost:8080/api/carfix/RFSListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-fedf5757-f32c-48d7-bb6d-3169e2911e231
###


POST http://localhost:8080/api/carfix/RegisterMemberService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
Content-Type: application/json

{
"uniqueId":"23141",
"firstName":"Test",
"lastName":"T",
"email":"julius3@test.com",
"username":"julius3@test.com",
"idnum": "1996",
"roleId": "5",
"userType": "MEMBER"
}
###




###
GET http://localhost:8080/api/carfix/ServiceProviderListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
###






POST http://localhost:8080/api/carfix/CreateQuoteService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
Content-Type: application/json

{
  "date":"12-12-2022",
  "requestForServiceId":"2343243254",
  "serviceProviderId":"234234543",
  "quotationTotal": "5000.00",
  "serviceProviderName": "serviceProviderName1",
  "quotationItems":[
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "id":"34234234",
      "quoteId":"23423434",
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    }
  ]
}
###


###
GET http://localhost:8080/api/carfix/QuoteListService?serviceProviderId=234234543
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
###


###
GET http://localhost:8080/api/carfix/QuoteListService?requestForServiceId=2343243254
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-0d46e02c-89f7-472b-8ee5-6a5cab7f43de1
Content-Type: application/json
###

GET http://localhost:8080/api/carfix/QuoteListService?quoteId=81e1e347-50f3-41e8-8be1-31774cddf0e0
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-0d46e02c-89f7-472b-8ee5-6a5cab7f43de1
###

GET http://localhost:8080/api/carfix/ServiceRequestOptionsListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###

POST http://localhost:8080/api/carfix/AcceptQuoteService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-3f4f5866-3f7a-443b-94d7-29f2c6d032a11
Content-Type: application/json

{
  "serviceRequestId": "303a67af-f8da-4030-9144-90c56bfc3caf",
  "acceptedQuoteId": "bbe4c739-9745-4243-8d7f-475fc5045722",
  "confirmedServiceProviderId":"bbf4c739-9745-4243-8d7f-475fc5045726"
}
###

POST http://localhost:8080/api/carfix/UpdateServiceRequestStatusService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-3f4f5866-3f7a-443b-94d7-29f2c6d032a11
Content-Type: application/json

{
"serviceRequestId": "303a67af-f8da-4030-9144-90c56bfc3caf",
"status": "SOME AMAZING status"
}
###





