
### dcd673bb-6f82-43c5-979c-df30da062562
POST https://cannacomply.connectmobiles24.com/api/oauth2/authorize
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Basic anVsaXVzQGNvbm5lY3Rtb2JpbGVzMjQuY29tOmRjZDY3M2JiLTZmODItNDNjNS05NzljLWRmMzBkYTA2MjU2Mg==
### API-ad757670-f1f8-4bcc-b879-3d511fbdc7b73

###
GET https://cannacomply.connectmobiles24.com/api/cannacomply/BlogListService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-a218e752-4047-429f-9cbe-133eddf1df763
Content-Type: application/json
###

###
GET https://cannacomply.connectmobiles24.com/api/cannacomply/CropListService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-ad757670-f1f8-4bcc-b879-3d511fbdc7b73
Content-Type: application/json
###


GET https://cannacomply.connectmobiles24.com/api/cannacomply/BlockListService?farmId=d5ccb179-dea5-47da-b5bf-811f46da057e
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-ad757670-f1f8-4bcc-b879-3d511fbdc7b73
Content-Type: application/json
###


GET https://cannacomply.connectmobiles24.com/api/cannacomply/ActivityListService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-1276a41e-de9c-45ed-bd8c-5b482f864c4c3
Content-Type: application/json
###

POST https://cannacomply.connectmobiles24.com/api/cannacomply/CreateActivityService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-7d87245c-63bf-4880-a32b-add93cd312db3
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "cropId":"394857539487",
  "type":"Richmond",
  "activityData":"[{},{},{},{}]",
  "userId":"9872387987234",
  "farmId": "farm-id-2",
  "date": "04-05-2023",
  "status": "CREATED"
}
###


###
POST https://cannacomply.connectmobiles24.com/api/cannacomply/UpdateSupplierService
X-API-Key:62e647ee-bd61-410e-9c66-adea21352f9f
Authorization:Bearer API-d4fb9a02-8e00-4f6b-92f2-f37b646c75e13
Content-Type: application/json
Farm-id:d5ccb179-dea5-47da-b5bf-811f46da056a

{
  "id": "9fc4dcd0-cd0b-487b-a9a5-c6e5df06b3ac",
  "farmId": "julius-nikiA23",
  "supplierName": "test supplier23",
  "productName": "test product23",
  "quantity": "20023",
  "expiryDate": "2022-12-12/23",
  "receipt":"test reciept3",
  "lotNumber": "lotNumber23",
  "container": "container23",
  "mass": "mass23"
}
###

