
###
POST http://localhost:8080/api/oauth2/authorize
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Basic YWRtaW4xNjY1MTQ1MTgzNzQ2OmRjZDY3M2JiLTZmODItNDNjNS05NzljLWRmMzBkYTA2MjU2Mg==
###


GET http://localhost:8080/api/carfix/VehicleListService?vehicleId=224d68f0-2629-430e-833e-215a54cb702c
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###



##
GET http://localhost:8080/api/carfix/VehicleListService?memberId=julius-niki
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###



POST http://localhost:8080/api/carfix/CreateVehicleService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-79c396c1-b96c-4cc0-a321-74f00e5715c91
Content-Type: application/json

{
  "vinNumber": "23432666456",
  "registration": "G3344d GP",
  "make": "Mercedes",
  "model": "year",
  "year": "2002",
  "fuelType": "petrol",
  "transmission": "manual",
  "odoReading": "2340333",
  "engineCode": "3043",
  "memberId": "julius-niki"
}
###


POST http://localhost:8080/api/carfix/UpdateVehicleService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6b1bf111-e864-4f4a-8efa-ae4918e622fe1
Content-Type: application/json

{
  "vehicleId": "224d68f0-2629-430e-833e-215a54cb702c",
  "vinNumber": "23432666456",
  "registration": "G3344d GP -UPDATED",
  "make": "Mercedes",
  "model": "year",
  "year": "2002 - UPDATED",
  "fuelType": "petrol",
  "transmission": "manual",
  "odoReading": "2340333",
  "engineCode": "3043",
  "memberId": "julius-niki"
}
###


###
POST http://localhost:8080/api/carfix/DeleteVehicleService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6b1bf111-e864-4f4a-8efa-ae4918e622fe1
Content-Type: application/json

{
  "vehicleId": "fe2cda48-75a7-4c5e-96f8-393b3101542a"
}
###




POST http://localhost:8080/api/carfix/CreateRFSService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-51653205-c123-4cc9-9e36-2b9f56e29dc11
Content-Type: application/json

{
  "date": "12-12-2022",
  "type": "REQUEST_FOR_SERVICE",
  "vehicleId": "4333e",
  "memberId": "334423",
  "radius": "10 KM",
  "status": "CREATED",
  "currentOdoReading": "234233.00",
  "pictureData": "base64Ecode(some data)",
  "additionalDescription": "need to change shocks",
  "lastServiceDate": "10-10-2021",
  "serviceRequestItems": [{"itemCategoryId": "34234234","itemDescription": "front shocks"},{"itemCategoryId": "34234234","itemDescription": "rear shocks"}]
}
###

###
GET http://localhost:8080/api/carfix/RFSListService?memberId=334423
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-3f4f5866-3f7a-443b-94d7-29f2c6d032a11
###

###
GET http://localhost:8080/api/carfix/RFSListService?vehicleId=4333e
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###


###
GET http://localhost:8080/api/carfix/RFSListService?serviceRequestId=303a67af-f8da-4030-9144-90c56bfc3caf
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-6874454d-c179-41e3-b205-1ce898c84da01
###

###
GET http://localhost:8080/api/carfix/RFSListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-fedf5757-f32c-48d7-bb6d-3169e2911e231
###


POST http://localhost:8080/api/carfix/RegisterMemberService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
Content-Type: application/json

{
"firstName":"Test",
"lastName":"T",
"email":"julius666566@test.com",
"username":"julius6665663@test.com",
"idnum": "1996",
"roleId": "5"
}
###

POST http://localhost:8080/api/carfix/RegisterServiceProviderService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
Content-Type: application/json

{
  "firstName":"Test",
  "lastName":"T",
  "email":"julius1295@test.com",
  "username":"julius1295@test.com",
  "idnum": "1996",
  "roleId": "5",
  "certifications": "certifications format?",
  "userType": "SERVICE_PROVIDER",
  "supportedBrands": [{"id": "b8367ced-5395-465a-8012-b55779285aa2"},{"id": "b8367ced-5395-465a-8012-b55779285aa2"}],
  "supportedCategories": [{"id": "b8367ced-5395-465a-8012-b55779285aa2"},{"id": "b8367ced-5395-465a-8012-b55779285ab2"}],
  "name": "SomeAmazingServiceProvider",
  "address": "1 Lobelia close bellville 7540",
  "aboutUs": "some information about the SP",
  "logoData": "encoded_logo_data"
}
###




###
GET http://localhost:8080/api/carfix/ServiceProviderListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
###

###
GET http://localhost:8080/api/carfix/ServiceProviderListService?id=de6e124f-e7c4-4882-af27-41ebd375a9cc
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
###






POST http://localhost:8080/api/carfix/CreateQuoteService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
Content-Type: application/json

{
  "date":"12-12-2022",
  "requestForServiceId":"2343243254",
  "serviceProviderId":"234234543",
  "quotationTotal": "5000.00",
  "serviceProviderName": "serviceProviderName1",
  "quotationItems":[
    {
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00",
      "quantity": "200"
    },
    {
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    },
    {
      "partNumber":"3323ASD",
      "partDescription":"23444.33",
      "itemTotalPrice": "2000.00"
    }
  ]
}
###


###
GET http://localhost:8080/api/carfix/QuoteListService?serviceProviderId=234234543
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-f5039f38-ec38-4db0-97a8-cfd27fb69c3f1
###


###
GET http://localhost:8080/api/carfix/QuoteListService?requestForServiceId=2343243254
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-0d46e02c-89f7-472b-8ee5-6a5cab7f43de1
Content-Type: application/json
###

GET http://localhost:8080/api/carfix/QuoteListService?quoteId=81e1e347-50f3-41e8-8be1-31774cddf0e0
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-0d46e02c-89f7-472b-8ee5-6a5cab7f43de1
###

GET http://localhost:8080/api/carfix/CategoryListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-111bddec-1137-49fb-822b-522530cf51a51
###

GET http://localhost:8080/api/carfix/BrandListService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-111bddec-1137-49fb-822b-522530cf51a51
###

POST http://localhost:8080/api/carfix/AcceptQuoteService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-3f4f5866-3f7a-443b-94d7-29f2c6d032a11
Content-Type: application/json

{
  "serviceRequestId": "303a67af-f8da-4030-9144-90c56bfc3caf",
  "acceptedQuoteId": "bbe4c739-9745-4243-8d7f-475fc5045722",
  "confirmedServiceProviderId":"bbf4c739-9745-4243-8d7f-475fc5045726"
}
###

POST http://localhost:8080/api/carfix/UpdateServiceRequestStatusService
X-API-Key:b67e14c8-093d-4502-8b10-d3c15c503200
Authorization:Bearer API-3f4f5866-3f7a-443b-94d7-29f2c6d032a11
Content-Type: application/json

{
"serviceRequestId": "303a67af-f8da-4030-9144-90c56bfc3caf",
"status": "SOME AMAZING status"
}
###




###
POST https://sandbox-l.ppay.io/api/oauth/token
Content-Type: application/json
Authorization: Basic Njc0YTI4OWQyMzU3MTFlYjkzZDUwMmQxNGRlMThjMGM6ZGNsN0U1Sk1mWWhaMU90OWlIdkdWakFrTlNVZ3NU
{
    "clientId": "674a289d235711eb93d502d14de18c0c",
    "clientSecret": "dcl7E5JMfYhZ1Ot9iHvGVjAkNSUgsT",
    "merchantId": "6749df69235711eb93d502d14de18c0c"
}
###


###
POST https://sandbox-l.ppay.io/api/channels/6749df69235711eb93d502d14de18c0c/payments
Content-Type: application/json

{
    "Authentication": {
    "userid": "674a289d235711eb93d502d14de18c0c",
    "password": "dcl7E5JMfYhZ1Ot9iHvGVjAkNSUgsT",
    "entityid": "6749df69235711eb93d502d14de18c0c"
  },
    "payment": {
        "merchantInvoiceId": "{{merchantInvoiceId}}",
        "amount": {{$randomPrice}},
        "currency": "ZAR",
        "files": [],
        "notes": "{{$randomBs}}"
    },
    "customer": {
        "givenName": "{{$randomFirstName}}",
        "surname": "{{$randomLastName}}",
        "email": "{{$randomEmail}}",
        "mobile": "+{{$randomPhoneNumber}}",
        "whatsapp": "+{{$randomPhoneNumber}}",
        "billing": {
            "street1": "{{$randomStreetAddress}}",
            "city": "{{$randomCity}}",
            "state": "{{$randomCountry}}",
            "postalCode": "{{$randomCreditCardMask}}",
            "country": "{{$randomCountryCode}}"
        }
    },
    "options": {
        "sendEmail": false,
        "sendSms": false,
        "sendWhatsapp": false,
        "emailCc": "{{$randomEmail}}",
        "emailBcc": "{{$randomEmail}}",
        "expiryTime": 5,
        "notificationUrl": "{{notificationUrl}}"
    },
    "checkout": {
        "defaultPaymentMethod": "CARD",
        "tokeniseCard": true
    }
}

###





